
CXX = g++
CXXFLAGS = -std=c++0x
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors
CXXFLAGS += -g

SRC1 = final_project.cpp
SRC2 = support.cpp
SRC3 = 
SRC4 = 
SRCS = ${SRC1} ${SRC2} ${SRC3} ${SRC4}

HEADER1 = final_support.h
HEADER2 = support.h
HEADER3 = 
HEADER4 = 
HEADERS = ${HEADER1} ${HEADER2} ${HEADER3} ${HEADER4}

PROG1 = main

default:
	${CXX} ${CXXFLAGS} ${SRCS} ${HEADERS} -o ${PROG1}