


make_clean:
	rm -f *.class
	
main_all: make_clean
	javac ResultPair.java
	javac DomainValidator.java
	javac RegexValidator.java
	javac InetAddressValidator.java
	javac UrlValidator.java
	javac testOutput.java
	javac test01.java
	java test01
	
main:
	javac testOutput.java
	javac test01.java
	java test01