
--SQL pulled and written by GWM on 17OCT2017

SELECT ReconciliationEO.RECONCILIATION_ACCOUNT_ID  AS "$ACCOUNT_ID$" ,
 R_ReconAttributes1.C_100000000261203  AS "Account" ,
 R_ReconAttributes1.C_100000000261204  AS "CoCd" ,
 ReconciliationEO.RECONCILIATION_NAME  AS "$NAME$" ,
 
	-- Field added by GWM
	SUBSTR(R_OrganizationUnitEO.ORG_NAME,1,3)  AS "Dept" ,
	
	-- Field added by GWM
	-- field "truePrep" for preparer
	-- when not found in Smry_Only_Query (when SRP = [None])
	CASE WHEN Smry_Only_Query.RECONCILIATION_ACCOUNT_ID IS NULL THEN
		
			-- get the non-smry preparer
			-- (this statement was generated by ARCS)
			(SELECT 
				CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN 
					ELSE FIRST_NAME||' '||LAST_NAME
				END				
				FROM FCM_USERS WHERE USER_ID = (coalesce(R_PreparerEO.ACTIVE_USER_ID, R_PreparerEO.USER_ID))
			)

		-- when found in Smry_Only_Query
		ELSE  Smry_Only_Query.SubPreparer

	END AS "truePrep",
	
	-- Field added by GWM
	-- field "trueRev" for reviewer
	-- when not found in Smry_Only_Query (when SRP = [None])
	CASE WHEN Smry_Only_Query.RECONCILIATION_ACCOUNT_ID IS NULL THEN
		
			-- get the non-smry reviewer
			-- (this statement was generated by ARCS)
			(SELECT
				CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN
					ELSE FIRST_NAME||' '||LAST_NAME
				END
				FROM FCM_USERS WHERE USER_ID = (coalesce(R_ReviewerEO1R.ACTIVE_USER_ID, R_ReviewerEO1R.USER_ID))
			)

		-- when found in Smry_Only_Query
		ELSE  Smry_Only_Query.SubReviewer

	END AS "trueRev",

 R_OrganizationUnitEO.ORG_NAME  AS "$ORGANIZATION_UNIT$" ,
 R_PeriodEO.PERIOD_NAME  AS "$PERIOD$" ,
 ((SELECT CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN ELSE FIRST_NAME||' '||LAST_NAME END FROM FCM_USERS WHERE USER_ID = (coalesce(R_PreparerEO.ACTIVE_USER_ID, R_PreparerEO.USER_ID))))  AS "$PREPARER$" ,
 (CASE CASE WHEN R_PreparerEO.USER_TYPE = 'U' THEN null ELSE CASE WHEN R_PreparerEO.ACTIVE_USER_ID is null THEN 'N' ELSE 'Y' END END WHEN 'N' THEN '$NO$' WHEN 'Y' THEN '$YES$'ELSE null END)  AS "$PREPARER_CLAIMED$" ,
 ((SELECT CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN ELSE FIRST_NAME||' '||LAST_NAME END FROM FCM_USERS WHERE USER_ID = (coalesce(R_ReviewerEO1R.ACTIVE_USER_ID, R_ReviewerEO1R.USER_ID))))  AS "$REVIEWER_LEVEL_TOKEN$" ,
 (CASE CASE WHEN R_ReviewerEO1R.USER_TYPE is null OR R_ReviewerEO1R.USER_TYPE = 'U' THEN null ELSE CASE WHEN R_ReviewerEO1R.ACTIVE_USER_ID is null THEN 'N' ELSE 'Y' END END WHEN 'N' THEN '$NO$' WHEN 'Y' THEN '$YES$'ELSE null END)  AS "$REVIEWER_LEVEL_CLAIMED$" ,
 CASE ReconciliationEO.SUMMARY_RECONCILIATION WHEN 'Y' THEN '$YES$' ELSE '$NO$' END  AS "$SUMMARY_PROFILE$" ,
 R_AttributeListValueEO11A.LIST_VALUE  AS "Summary Recon Parent" ,
 R_AttributeListValueEO13A.LIST_VALUE  AS "Exclusion" 

 FROM ARM_RECONCILIATIONS ReconciliationEO 
LEFT OUTER JOIN ARM_RECON_ATTRIBUTES_1 R_ReconAttributes1 ON (ReconciliationEO.RECONCILIATION_ID = R_ReconAttributes1.OBJECT_ID)
LEFT OUTER JOIN FCM_ORG_UNITS R_OrganizationUnitEO ON (ReconciliationEO.ORG_ID = R_OrganizationUnitEO.ORG_ID)
LEFT OUTER JOIN ARM_PERIODS R_PeriodEO ON (ReconciliationEO.PERIOD_ID = R_PeriodEO.PERIOD_ID)
LEFT OUTER JOIN ARM_ACCESS R_PreparerEO ON (ReconciliationEO.RECONCILIATION_ID = R_PreparerEO.OBJECT_ID AND R_PreparerEO.ACCESS_TYPE = 'P')
LEFT OUTER JOIN ARM_ACCESS R_ReviewerEO1R ON (ReconciliationEO.RECONCILIATION_ID = R_ReviewerEO1R.OBJECT_ID AND R_ReviewerEO1R.ACCESS_TYPE = 'R' AND R_ReviewerEO1R.ACCESS_ORDER = 1)
LEFT OUTER JOIN FCM_ATTRIBUTE_LIST_VALUES R_AttributeListValueEO11A ON (R_ReconAttributes1.C_100000000263227 = R_AttributeListValueEO11A.LIST_VALUE_ID)
LEFT OUTER JOIN FCM_ATTRIBUTE_LIST_VALUES R_AttributeListValueEO13A ON (R_ReconAttributes1.C_100000002700010 = R_AttributeListValueEO13A.LIST_VALUE_ID)

-- Join added by GWM
LEFT OUTER JOIN (
	
	-- Fields used
	
	SELECT ReconciliationEO_sub.RECONCILIATION_ACCOUNT_ID,
	((SELECT CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN ELSE FIRST_NAME||' '||LAST_NAME END FROM FCM_USERS WHERE USER_ID = (coalesce(R_PreparerEO_sub.ACTIVE_USER_ID, R_PreparerEO_sub.USER_ID))))  AS SubPreparer ,
	((SELECT CASE WHEN FIRST_NAME IS NULL AND LAST_NAME IS NULL THEN USER_LOGIN ELSE FIRST_NAME||' '||LAST_NAME END FROM FCM_USERS WHERE USER_ID = (coalesce(R_ReviewerEO1R_sub.ACTIVE_USER_ID, R_ReviewerEO1R_sub.USER_ID))))  AS SubReviewer ,
	
	-- Fields NOT used
	
	R_PeriodEO_sub.PERIOD_NAME,
	(CASE CASE WHEN R_PreparerEO_sub.USER_TYPE = 'U' THEN null ELSE CASE WHEN R_PreparerEO_sub.ACTIVE_USER_ID is null THEN 'N' ELSE 'Y' END END WHEN 'N' THEN '$NO$' WHEN 'Y' THEN '$YES$'ELSE null END)  AS SubPrepClaimed ,
	(CASE CASE WHEN R_ReviewerEO1R_sub.USER_TYPE is null OR R_ReviewerEO1R_sub.USER_TYPE = 'U' THEN null ELSE CASE WHEN R_ReviewerEO1R_sub.ACTIVE_USER_ID is null THEN 'N' ELSE 'Y' END END WHEN 'N' THEN '$NO$' WHEN 'Y' THEN '$YES$'ELSE null END)  AS SubRevClaimed ,
	CASE ReconciliationEO_sub.SUMMARY_RECONCILIATION WHEN 'Y' THEN '$YES$' ELSE '$NO$' END  AS SubSummaryProfile ,
	R_AttributeListValueEO11A_sub.LIST_VALUE  AS SubSummaryReconParent ,
	R_AttributeListValueEO13A_sub.LIST_VALUE  AS SubExclusion 
	
	-- Source and joins
	
	FROM ARM_RECONCILIATIONS ReconciliationEO_sub 
	LEFT OUTER JOIN ARM_RECON_ATTRIBUTES_1 R_ReconAttributes1_sub ON (ReconciliationEO_sub.RECONCILIATION_ID = R_ReconAttributes1_sub.OBJECT_ID)
	LEFT OUTER JOIN ARM_PERIODS R_PeriodEO_sub ON (ReconciliationEO_sub.PERIOD_ID = R_PeriodEO_sub.PERIOD_ID)
	LEFT OUTER JOIN ARM_ACCESS R_PreparerEO_sub ON (ReconciliationEO_sub.RECONCILIATION_ID = R_PreparerEO_sub.OBJECT_ID AND R_PreparerEO_sub.ACCESS_TYPE = 'P')
	LEFT OUTER JOIN ARM_ACCESS R_ReviewerEO1R_sub ON (ReconciliationEO_sub.RECONCILIATION_ID = R_ReviewerEO1R_sub.OBJECT_ID AND R_ReviewerEO1R_sub.ACCESS_TYPE = 'R' AND R_ReviewerEO1R_sub.ACCESS_ORDER = 1)
	LEFT OUTER JOIN FCM_ATTRIBUTE_LIST_VALUES R_AttributeListValueEO11A_sub ON (R_ReconAttributes1_sub.C_100000000263227 = R_AttributeListValueEO11A_sub.LIST_VALUE_ID)
	LEFT OUTER JOIN FCM_ATTRIBUTE_LIST_VALUES R_AttributeListValueEO13A_sub ON (R_ReconAttributes1_sub.C_100000002700010 = R_AttributeListValueEO13A_sub.LIST_VALUE_ID)
	WHERE (ReconciliationEO_sub.PERIOD_ID <> -2)
	AND ((((ReconciliationEO_sub.PERIOD_ID  =  ~PERIOD~ ))))
	
	-- Only where Smry = 'Y'
	AND (ReconciliationEO_sub.SUMMARY_RECONCILIATION = 'Y')
	
) Smry_Only_Query
ON (R_AttributeListValueEO11A.LIST_VALUE = Smry_Only_Query.RECONCILIATION_ACCOUNT_ID)


WHERE (ReconciliationEO.PERIOD_ID <> -2)
AND ((((ReconciliationEO.PERIOD_ID  =  ~PERIOD~ )))) 

--GWM added ORDER BY criteria
ORDER BY
	--Sort [None] to the top ('0000000'<anything)
	CASE WHEN R_AttributeListValueEO11A.LIST_VALUE = '[None]' THEN '0000000'
	
		ELSE R_AttributeListValueEO11A.LIST_VALUE
	END ASC,

	--Sort Summary recons to the bottom ('N'<'Y')
	ReconciliationEO.SUMMARY_RECONCILIATION ASC,
	
	--Sort by account number
	R_ReconAttributes1.C_100000000261203 ASC
	
	

