default: all
all:
	gcc -Wall -std=c99 -o Q0 Q0.c
	gcc -Wall -std=c99 -o Q1 Q1.c
	gcc -Wall -std=c99 -o Q2 Q2.c
	gcc -Wall -std=c99 -o Q3 Q3.c
	gcc -Wall -std=c99 -o Q4 Q4.c
	gcc -Wall -std=c99 -o Q5 Q5.c

